### ISSUE TITLE
SCSS VERSION

### ISSUE THREAD

**Issue by ascito** [Lcfvs/css-ui#1]
a code base may be perfect if you propose a .scss version of your collection.

I enjoy, you learn "How to" here for exemple:
https://sass-lang.com/guide

good luck :)

**Comment by Lcfvs** [comment]
You can make a pull request with the scss versions of my modules.

But, please, don't declare non-generic other properties than these.

;)

**Comment by Lcfvs** [comment]
As discussed, I close this issue, send your pull request when you want. ;)
